
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../types/supabase';

const SUPABASE_URL = "https://ezxkzvjqbulajgwynbub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6eGt6dmpxYnVsYWpnd3luYnViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3Njc5OTUsImV4cCI6MjA1OTM0Mzk5NX0.c1SKW4CgZWs32ARG6I53rjOraun_hU6jhiaixCuEkyg";

// Import the supabase client like this:
// import { supabase } from "@/lib/supabase";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
